# Generated by Django 4.1.3 on 2022-12-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserform',
            name='date_born',
        ),
        migrations.RemoveField(
            model_name='customuserform',
            name='kind_of_pet',
        ),
        migrations.AlterField(
            model_name='customuserform',
            name='owner_fathername',
            field=models.CharField(max_length=50, verbose_name='Отчество владельца'),
        ),
    ]
