# Generated by Django 4.1.3 on 2023-01-10 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsJobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctors_job_title', models.CharField(max_length=100, verbose_name='Полная  должность врача')),
            ],
            options={
                'verbose_name': 'Должность врача',
                'verbose_name_plural': 'Должность врачей',
            },
        ),
        migrations.CreateModel(
            name='KindOfPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_pet', models.CharField(max_length=20, null=True, verbose_name='Вид животного')),
            ],
            options={
                'verbose_name': 'Вид животного',
                'verbose_name_plural': 'Вид животного',
            },
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_nickname', models.CharField(max_length=50, verbose_name='Кличка животного')),
                ('pet_gender', models.CharField(choices=[('f', 'Женский'), ('m', 'Мужской')], max_length=1, verbose_name='Пол животного')),
                ('pet_age', models.IntegerField(verbose_name='Возраст животного')),
                ('kind_of_pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients_data.kindofpet', verbose_name='Вид животного')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
    ]
