# Generated by Django 4.1.3 on 2022-12-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsJobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctors_job_title', models.CharField(max_length=100, verbose_name='Полная  должность врача')),
            ],
            options={
                'verbose_name': 'Должность врача',
                'verbose_name_plural': 'Должность врачей',
            },
        ),
        migrations.CreateModel(
            name='KindOfPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_pet', models.CharField(max_length=20, null=True, verbose_name='Вид животного')),
            ],
            options={
                'verbose_name': 'Вид животного',
                'verbose_name_plural': 'Вид животного',
            },
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_age', models.IntegerField(verbose_name='Возраст животного')),
                ('pet_nickname', models.CharField(max_length=100, verbose_name='Кличка животного')),
                ('pet_gender', models.CharField(choices=[('f', 'Женский'), ('m', 'Мужской')], max_length=1, verbose_name='Пол животного')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=30, verbose_name='Имя доктора')),
                ('doctor_lastname', models.CharField(max_length=50, verbose_name='Фамилия доктора')),
                ('doctor_fathername', models.CharField(max_length=50, verbose_name='Отчество доктора')),
                ('doctor_tel', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('doctor_email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('doctor_foto', models.ImageField(upload_to='clients_data/doctors', verbose_name='Фотография')),
                ('doctor_job_title', models.ManyToManyField(to='clients_data.doctorsjobtitle', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
            },
        ),
    ]
