# Generated by Django 4.1.3 on 2023-01-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='pet_gender',
            field=models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский')], max_length=1, verbose_name='Пол животного'),
        ),
    ]
