# Generated by Django 4.1.3 on 2023-01-10 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=140, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория лекарства',
                'verbose_name_plural': 'Категория лекарств',
            },
        ),
        migrations.CreateModel(
            name='Medicine_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=140, verbose_name='Лекарственная форма')),
            ],
            options={
                'verbose_name': 'Лекарственная форма',
                'verbose_name_plural': 'Лекарственая форма',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_medicine', models.CharField(max_length=100, verbose_name='Название лекарства')),
                ('manufacturer', models.CharField(max_length=200, verbose_name='Производитель')),
                ('descriptions', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('expiration_data', models.DateField(verbose_name='Дата окончания срока годности')),
                ('count', models.IntegerField(blank=True, default='0', verbose_name='Количество')),
                ('barcode', models.ImageField(blank=True, height_field='98px', upload_to='media/medicines_barcode/', verbose_name='Штрихкод товара', width_field='141px')),
                ('medicine_img', models.ImageField(blank=True, upload_to='media/medicine_img/', verbose_name='Изображения лекарства')),
                ('code', models.CharField(blank=True, max_length=48, verbose_name='Штрих-код(цифры)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet_pharmacy.medicine_category', verbose_name='Категория лекарства')),
            ],
            options={
                'verbose_name': 'Лекарства',
                'verbose_name_plural': 'Лекарства',
            },
        ),
    ]
