# Generated by Django 4.1.3 on 2023-01-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'ordering': ('title_medicine',), 'verbose_name': 'Лекарства', 'verbose_name_plural': 'Лекарства'},
        ),
        migrations.AddField(
            model_name='medicine_category',
            name='slug_category',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicine_category',
            name='category',
            field=models.CharField(db_index=True, max_length=140, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='title_medicine',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название лекарства'),
        ),
        migrations.AlterIndexTogether(
            name='pharmacy',
            index_together={('id', 'slug')},
        ),
    ]
