# Generated by Django 4.1.3 on 2022-12-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='medicine',
            new_name='title_medicine',
        ),
    ]
