# Generated by Django 4.1.3 on 2022-12-09 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet_pharmacy', '0002_rename_medicine_pharmacy_title_medicine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine_category',
            options={'verbose_name': 'Категория лекарства', 'verbose_name_plural': 'Категория лекарств'},
        ),
        migrations.AlterModelOptions(
            name='medicine_form',
            options={'verbose_name': 'Лекарственная форма', 'verbose_name_plural': 'Лекарственая форма'},
        ),
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'verbose_name': 'Лекарства', 'verbose_name_plural': 'Лекарства'},
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='medicine_img',
            field=models.ImageField(blank=True, upload_to='media/medicine_img/', verbose_name='Изображения лекарства'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pet_pharmacy.medicine_category', verbose_name='Категория лекарства'),
        ),
    ]
