# Generated by Django 4.1.3 on 2023-01-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_pharmacy', '0002_alter_pharmacy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_category',
            name='slug_category',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='count',
            field=models.IntegerField(default='0', verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
