# Generated by Django 4.1.3 on 2022-12-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_pharmacy', '0003_alter_medicine_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='code',
            field=models.CharField(blank=True, max_length=48, verbose_name='Штрих-код(цифры)'),
        ),
    ]
