# Generated by Django 4.1.3 on 2023-01-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_receptions', models.DateTimeField(auto_now_add=True, verbose_name='Дата приема')),
                ('rec_diagnose', models.CharField(max_length=100, verbose_name='Диагноз')),
                ('rec_instructions', models.TextField(verbose_name='Указания')),
                ('send_pdf_reciev_copy', models.BooleanField(blank=True, verbose_name='Отправить копию бланка приема на почту')),
            ],
            options={
                'verbose_name': 'Прием',
                'verbose_name_plural': 'Приемы',
            },
        ),
        migrations.CreateModel(
            name='RecieveRequsetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derscription', models.TextField(verbose_name='Описание проблемы')),
                ('data_to_come', models.DateField(verbose_name='Дата записи')),
                ('time_to_come', models.TimeField(verbose_name='Время записи')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Подтверждено'), ('CANCELED', 'Отменена'), ('FINISH', 'Готово'), ('NEW', 'Новая заявка'), ('NULL', 'Анулированна'), ('IN_PROCESS', 'В процессе')], default='Новая заявка', max_length=12)),
            ],
            options={
                'verbose_name': 'Заявка на прием',
                'verbose_name_plural': 'Заявки на прием',
            },
        ),
    ]
