# Generated by Django 4.1.3 on 2022-12-03 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reception', '0001_initial'),
        ('clients_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receptions',
            name='owner_lastname_rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Фамилия владельца'),
        ),
        migrations.AddField(
            model_name='receptions',
            name='owner_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL, verbose_name='Имя владельца'),
        ),
        migrations.AddField(
            model_name='receptions',
            name='pet_gender_rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients_data.kindofpet', verbose_name='Вид животного'),
        ),
        migrations.AddField(
            model_name='receptions',
            name='pet_nickname_rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nick_names', to='clients_data.pets', verbose_name='Кличка животного'),
        ),
    ]
