# Generated by Django 4.1.3 on 2022-12-19 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reception', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieverequsetmodel',
            name='email_recive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails_recieve', to=settings.AUTH_USER_MODEL, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='recieverequsetmodel',
            name='pet_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pets_name', to=settings.AUTH_USER_MODEL, verbose_name='Имя питомца'),
        ),
        migrations.AlterField(
            model_name='recieverequsetmodel',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Подтверждено'), ('CANCELED', 'Отменена'), ('NULL', 'Анулированна'), ('NEW', 'Новая заявка'), ('IN_PROCESS', 'В процессе'), ('FINISH', 'Готово')], default='Новая заявка', max_length=12),
        ),
        migrations.AlterField(
            model_name='recieverequsetmodel',
            name='tel_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tel', to=settings.AUTH_USER_MODEL, verbose_name='Номер телефона'),
        ),
    ]
