# Generated by Django 4.1.3 on 2022-11-25 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients_data', '0001_initial'),
        ('reception', '0002_alter_receptions_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptions',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients_data.doctors'),
        ),
        migrations.AlterField(
            model_name='receptions',
            name='doctor_job_title_rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_title', to='clients_data.doctorsjobtitle'),
        ),
        migrations.AlterField(
            model_name='receptions',
            name='kind_of_pet_rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Kinde_pet', to='clients_data.kindofpet', verbose_name='Вид животного'),
        ),
    ]
