# Generated by Django 4.1.3 on 2022-11-26 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients_data', '0001_initial'),
        ('reception', '0003_alter_receptions_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptions',
            name='doctor_job_title_rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_titles', to='clients_data.doctorsjobtitle'),
        ),
        migrations.AlterField(
            model_name='receptions',
            name='kind_of_pet_rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Kinde_pets', to='clients_data.kindofpet', verbose_name='Вид животного'),
        ),
        migrations.AlterField(
            model_name='receptions',
            name='owner_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='clients_data.clientsdata', verbose_name='Имя владельца'),
        ),
        migrations.AlterField(
            model_name='receptions',
            name='pet_nickname_rec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nick_names', to='clients_data.pets', verbose_name='Кличка животного'),
        ),
    ]
