# Generated by Django 4.1.3 on 2023-01-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_recieverequsetmodel_reception_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieverequsetmodel',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Подтверждено'), ('FINISH', 'Готово'), ('CANCELED', 'Отменена'), ('NULL', 'Анулированна'), ('NEW', 'Новая заявка'), ('IN_PROCESS', 'В процессе')], default='Новая заявка', max_length=12),
        ),
    ]
