# Generated by Django 4.1.3 on 2022-12-20 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients_data', '0001_initial'),
        ('reception', '0003_alter_recieverequsetmodel_email_recive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieverequsetmodel',
            name='pet_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pets_name', to='clients_data.pets', verbose_name='Имя питомца'),
        ),
        migrations.AlterField(
            model_name='recieverequsetmodel',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Подтверждено'), ('NEW', 'Новая заявка'), ('IN_PROCESS', 'В процессе'), ('CANCELED', 'Отменена'), ('FINISH', 'Готово'), ('NULL', 'Анулированна')], default='Новая заявка', max_length=12),
        ),
    ]
