# Generated by Django 4.1.3 on 2023-01-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0006_alter_recieverequsetmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieverequsetmodel',
            name='status',
            field=models.CharField(choices=[('CANCELED', 'Отменена'), ('FINISH', 'Готово'), ('IN_PROCESS', 'В процессе'), ('NEW', 'Новая заявка'), ('CONFIRMED', 'Подтверждено'), ('NULL', 'Анулированна')], default='Новая заявка', max_length=12),
        ),
    ]
