# Generated by Django 4.1.3 on 2023-01-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0009_alter_recieverequsetmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieverequsetmodel',
            name='status',
            field=models.CharField(choices=[('FINISH', 'Готово'), ('IN_PROCESS', 'В процессе'), ('NEW', 'Новая заявка'), ('NULL', 'Анулированна'), ('CANCELED', 'Отменена'), ('CONFIRMED', 'Подтверждено')], default='Новая заявка', max_length=12),
        ),
    ]
