# Generated by Django 4.1.3 on 2023-01-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0010_alter_recieverequsetmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieverequsetmodel',
            name='status',
            field=models.CharField(choices=[('NULL', 'Анулированна'), ('CANCELED', 'Отменена'), ('IN_PROCESS', 'В процессе'), ('CONFIRMED', 'Подтверждено'), ('FINISH', 'Готово'), ('NEW', 'Новая заявка')], default='Новая заявка', max_length=12),
        ),
    ]
