# Generated by Django 4.1.3 on 2023-01-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0014_alter_recieverequsetmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieverequsetmodel',
            name='status',
            field=models.CharField(choices=[('FINISH', 'Готово'), ('CONFIRMED', 'Подтверждено'), ('IN_PROCESS', 'В процессе'), ('NULL', 'Анулированна'), ('NEW', 'Новая заявка'), ('CANCELED', 'Отменена')], default='Новая заявка', max_length=12),
        ),
    ]
