# Generated by Django 4.1.3 on 2023-01-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0015_alter_recieverequsetmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieverequsetmodel',
            name='status',
            field=models.CharField(choices=[('CANCELED', 'Отменена'), ('NULL', 'Анулированна'), ('CONFIRMED', 'Подтверждено'), ('NEW', 'Новая заявка'), ('IN_PROCESS', 'В процессе'), ('FINISH', 'Готово')], default='Новая заявка', max_length=12),
        ),
    ]
