# Generated by Django 4.1.3 on 2023-01-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0017_alter_recieverequsetmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieverequsetmodel',
            name='status',
            field=models.CharField(choices=[('FINISH', 'Готово'), ('CANCELED', 'Отменена'), ('IN_PROCESS', 'В процессе'), ('CONFIRMED', 'Подтверждено'), ('NULL', 'Анулированна'), ('NEW', 'Новая заявка')], default='Новая заявка', max_length=12),
        ),
    ]
